version: 2
jobs:
  build:
    working_directory: ~/wipefest
    docker:
      - image: joshyaxley/angular-cli
    steps:
      - checkout
      - restore_cache:
          keys:
            - wipefest-npm-deps-{{ .Branch }}-{{ checksum "package.json" }}
            - wipefest-npm-deps-{{ .Branch }}
            - wipefest-npm-deps-
      - run: npm install
      - save_cache:
          key: wipefest-npm-deps-{{ checksum "package.json" }}
          paths:
            - .node_modules
      - run: ng build
      - run: ls dist
      - deploy:
          name: Development
          command: sh deploy.sh